openapi: 3.0.0
info:
  title: Social+ Cloud SDK
  description: |
    ## Using Social+ APIs

    Our API documentation explains all API endpoints used in Social+ Cloud. All APIs, with the exception of some authentication APIs, require an access token for authentication and authorization. APIs can be used either in Admin or User context. When used in user context, you will only be able to fetch data related to that user only.
    For Administrators who are using our API documentation in making server-to-server API calls, you need an Admin Access token to connect to the Social+ server. Refer to
    [this documentation](https://docs.social.plus/console/settings#admin-api-access-token)
    for the instructions on how to generate an admin access token.

    All backend endpoints that support Social+ Cloud SDK are included here. To easily differentiate the type of each endpoint, we added a prefix in each endpoint's path.

    - REST API Endpoint: **`/v1, /v2, /v3, /v4, or /v5 ...`**
    - Webhook Event: **`/webhook ...`**

    ---

    ## **Schema Definitions**

    This section provides detailed descriptions of the key schemas used in Social+ Cloud. Understanding these schemas is essential for effectively integrating our features into your applications. Each schema entry includes a concise description and highlights its core functionality and relationships within the platform. These definitions will help you grasp the structure and purpose of various components, ensuring a seamless and efficient development experience.

    ### **User**

    A User represents an individual who interacts with the Social+ Cloud. Users can create profiles, join communities, post content, comment, react, and engage with other users.

    ### **Role**

    A Role defines the permissions and access levels for Users within the Social+ Cloud. Roles can be assigned to manage and moderate content, ensuring a controlled and safe environment for all users.

    ### **Channel**

    A Channel is a primary structure used to implement various chat messaging capabilities within an application. Channels serve as containers for Subchannels, enabling a hierarchical organization of conversations. This structure allows developers to manage and navigate different chat threads efficiently.

    ### **Subchannel**

    A Subchannel is a subdivision within a Channel for specific conversation threads. Subchannels host all messages and interactions, providing organized discussions within a larger channel. Users can individually create, update, delete, and manage subchannels. Moderation actions, such as banning and muting, are applied at the channel level, affecting all subchannels.

    ### **ChannelUser**

    A ChannelUser represents an individual user within a specific Channel. This schema tracks user participation, roles, and permissions within the channel. Each ChannelUser can interact in subchannels, participate in discussions, and engage with other members. Users can be assigned roles with varying permissions, such as admin, moderator, or member, allowing for tailored access and control. Moderation actions like banning or muting a ChannelUser affect their participation across all subchannels within the channel.

    ### **Message**

    A Message facilitates real-time communication among channel users. Messages can contain up to 20,000 characters or weigh up to 100KB for custom content. For larger binary data, such as files, it's recommended to upload the data to a cloud storage service like AWS S3 and include the URL in the message. The SDK supports various message types, including text and image, built on a standard message layer.

    ### **Community**

    A Community is a feature that allows users to share their posts and comments and engage with each other within the app. Communities provide a dedicated space for discussing specific topics or interests.

    ### **CommunityUser**

    A CommunityUser represents an individual user within a specific Community. This schema tracks user participation, roles, and interactions within the community. CommunityUsers can join public or private communities, participate in discussions, and engage with other members. Each user can have different roles with varying permissions, such as admin, moderator, or member, which control their access and actions within the community. Moderation actions, like banning or muting, can be applied to CommunityUsers to maintain a safe and respectful environment.

    ### **CommunityCategory**

    A CommunityCategory helps organize and manage communities by categorizing them into specific groups. This categorization allows users to easily sort and filter communities based on their interests or needs.

    ### **Post**

    A Post is a piece of content created and shared by a user within a network or community. Posts can include text, images, videos, or other elements. Users can create, view, and interact with posts in a social feed, which can be displayed in chronological order and customized using various settings. Post types supported by Social+ include text, image, video, file, live stream, poll, and custom posts. The parent post serves as a container for text data, while each multimedia element (e.g., image, video) is treated as a separate child post. Both parent and child posts support reactions and comments, allowing users to engage comprehensively with content.

    ### **Comment**

    A Comment in Social+ Cloud is a user-generated response to specific content, such as a post or story. Comments enable users to engage in conversations, express thoughts, opinions, and emotions, fostering a sense of community around the content.

    **Comment Reference Types:**

    - **Post Type Comment:** Designed for regular posts like text updates, photos, or videos. These comments are associated with the post and displayed beneath it, promoting conversation and interaction.
    - **Story Type Comment:** Similar to post type comments but associated with stories, driving user engagement and discussion around short-lived content.
    - **Content Type Comment:** Intended for content-specific such as articles or specialized content, providing a more organized and contextual commenting experience.

    ### **Reaction**

    A Reaction is a user interaction on messages, posts, or comments, such as like, dislike, or love. The type of reactions is customizable. Currently, reactions are supported for Posts, Messages, and Comments.

    **Reaction Reference Types:**

    - **Comment Reference Type:** Allows users to query reactions on a specific comment, showing how others have responded to it.
    - **Post Reference Type:** Allows users to query reactions on a specific post, highlighting user engagement with the post.
    - **Story Reference Type:** Allows users to query reactions on a specific story, showing user reactions to the story.

    ### **File**

    A File in Social+ Cloud supports file upload and download, enabling file-sharing within applications. It handles various file types, including images, videos, audio, and documents, with a maximum size of 1 GB. This functionality allows users to share files directly in chats or social feeds, enhancing engagement and interaction.

    ### **Follow**

    A Follow schema in Social+ Cloud defines one-directional relationships between users, essential for social networking features. When user A follows user B, user A can see user B's updates in their feed, but user B does not need to reciprocate. This schema helps manage visibility and accessibility of user-generated content in user feeds.

    ---

    ## Select Region Endpoint

    Before making server-to-server API calls, be sure to select the correct API endpoint for your region in the **Servers** dropdown below.
  version: 4.99.1
servers:
  - url: https://apix.us.amity.co
    description: API Endpoint for US Region
  - url: https://apix.eu.amity.co
    description: API Endpoint for EU Region
  - url: https://apix.sg.amity.co
    description: API Endpoint for SG Region
paths:
  /admin/v1/moderation-feeds:
    get:
      summary: Get moderation feeds
      description: Get moderation feeds.
      tags:
        - Moderation Feed
      security:
        - cookieAuth: []
      parameters:
        - name: targetType
          in: query
          schema:
            type: string
            enum:
              - user
              - community
        - name: targetIds
          in: query
          description: Target internal id
          schema:
            type: array
            items:
              type: string
              maxLength: 900
        - name: contentTypes
          in: query
          schema:
            type: array
            items:
              type: string
              enum:
                - post
                - comment
                - image
                - video
                - file
        - name: creatorIds
          in: query
          description: Creator internal id
          schema:
            type: array
            items:
              type: string
              maxLength: 900
        - name: tags
          in: query
          schema:
            type: array
            items:
              type: string
              maxLength: 24
            max: 5
        - name: isDeleted
          in: query
          description: |
            For filter content that is deleted while reviewing <br>
            Will filter manualReview.reviewedType == 'deleted' || aiModeration.moderatedAction == 'deleted'
          schema:
            type: boolean
        - name: isFlagCleared
          in: query
          description: |
            For filter content that flag is cleared while reviewing <br>
            Will filter manualReview.reviewedType == "clearFlag"
          schema:
            type: boolean
        - name: isReviewed
          in: query
          description: |
            For filter content that is reviewed or not reviewed <br>
            Will filter lastReviewedAt exists
          schema:
            type: boolean
        - name: options[token]
          in: query
          description: Token for pagination. Use the token from the previous response to get the next page.
          schema:
            type: string
            maxLength: 1000
        - name: options[limit]
          in: query
          description: Limit the number of items in the response. Default is 20.
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sortBy[type]
          in: query
          description: Sort by type.
          schema:
            type: string
            default: lastFlaggedAt
            enum:
              - lastFlaggedAt
              - flagCount
              - lastReviewedAt
        - name: sortBy[order]
          in: query
          description: Sort order. Default is desc.
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        '200':
          $ref: '#/components/responses/root-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/network-settings/premium-reports:
    get:
      summary: Get premium report settings
      description: Get premium report settings.
      tags:
        - Premium Report
      security:
        - cookieAuth: []
      responses:
        '200':
          $ref: '#/components/responses/premium-reports-get-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/premium-reports:
    get:
      summary: Query report items
      description: Retrieve the existing report
      tags:
        - Premium Report
      security:
        - cookieAuth: []
      parameters:
        - name: options[token]
          in: query
          description: Next page token for pagination.
          required: false
          schema:
            type: string
            example: 1w41l63U0xa8q7smH50vCxyTQqdxo69O3EmK28Bi5PcROI4wI/EyIJg==
            maxLength: 1000
        - name: options[limit]
          in: query
          description: The limit for the number of report items.
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          $ref: '#/components/responses/root-get-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/premium-reports/download:
    get:
      summary: Download report item
      description: Download the report item from S3
      tags:
        - Premium Report
      security:
        - cookieAuth: []
      parameters:
        - name: fileName
          in: query
          description: Base64 encoded file name of the report items.
          required: true
          schema:
            type: string
            example: c2FtcGxlLXRleHQtZmlsZS5qcGc=
      responses:
        '302':
          $ref: '#/components/responses/download-response-302'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /internal/v1/premium-reports/list-networks:
    get:
      summary: List enabled networks
      description: List networks that have the premium report enabled.
      parameters:
        - name: x-caller-context
          in: header
          description: The caller context header is used to identify the caller context. Must be a JSON string.
          required: true
          type: string
          example: |
            {}
      tags:
        - Premium Report
      security:
        - basicAuth: []
      responses:
        '200':
          $ref: '#/components/responses/list-networks-get-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /internal/v1/network-settings/premium-report:
    put:
      summary: Update premium report settings
      description: Update premium report settings.
      tags:
        - Premium Report
      security:
        - basicAuth: []
      parameters:
        - name: x-internal-api-key
          in: header
          description: The internal API key of network to update
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                  description: |
                    Whether the premium report is enabled or not.
                  example: true
                  default: false
      responses:
        '200':
          $ref: '#/components/responses/premium-reports-put-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/admin:
    post:
      summary: Create a new admin user
      description: Creates a new admin user with the specified details and permissions.
      tags:
        - Admin
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username for the new admin.
                  example: newadmin
                displayName:
                  type: string
                  description: The display name for the new admin.
                  example: New Admin
                password:
                  type: string
                  description: The password for the new admin.
                  example: securepassword123
                firstname:
                  type: string
                  description: The first name of the new admin.
                  example: John
                lastname:
                  type: string
                  description: The last name of the new admin.
                  example: Doe
                permissions:
                  type: array
                  items:
                    type: string
                  description: List of permissions assigned to the new admin.
                  example:
                    - VIEW_DYNAMIC_UI
                    - VIEW_CHANNEL_MANAGEMENT
                    - MANAGE_CHANNEL
                    - MODERATE_CHANNEL
                    - VIEW_STORY_MANAGEMENT
                    - MANAGE_STORY
                    - VIEW_POST_AND_COMMENT_MANAGEMENT
                    - MODERATE_POST_AND_COMMENT
                    - MANAGE_POST_AND_COMMENT
                    - CAN_USE_BRAND_USERS
                    - CAN_MANAGE_BRAND_USERS
                    - CAN_MANAGE_GLOBAL_PINNED_POST
                    - CAN_MANAGE_PINNED_POST
                    - CAN_MANAGE_FEATURED_POST
                    - VIEW_LIVE_STREAMING_MANAGEMENT
                    - MANAGE_LIVE_STREAMING
                    - MODERATE_LIVE_STREAMING
                    - VIEW_COMMUNITY_MANAGEMENT
                    - MANAGE_COMMUNITY
                    - MODERATE_COMMUNITY
                    - DELETE_COMMUNITY
                    - VIEW_COMMUNITY_CATEGORY_MANAGEMENT
                    - MANAGE_COMMUNITY_CATEGORY
                    - VIEW_SPONSORED_CONTENT_MANAGEMENT
                    - MANAGE_SPONSORED_CONTENT
                    - MANAGE_AD_SETTING
                    - VIEW_USAGE
                    - VIEW_MODERATION_FEED
                    - MANAGE_ALLOW_LIST
                    - MANAGE_BLOCK_LIST
                    - MANAGE_IMAGE_MODERATION_SETTING
                    - MANAGE_LIVE_STREAMING_MODERATION_SETTING
                    - VIEW_USER_MANAGEMENT
                    - MANAGE_USER
                    - MODERATE_USER
                    - VIEW_USER_ROLE_MANAGEMENT
                    - MANAGE_USER_ROLE
                    - VIEW_ADMIN_USER
                    - MANAGE_ADMIN
                    - VIEW_ADMIN_ROLE
                    - VIEW_SETTING
                    - MANAGE_SETTING
                    - MANAGE_SECURITY
                avatarFileId:
                  type: string
                  description: The file ID of the avatar for the new admin.
                  example: file-12345
                roleAssignments:
                  type: array
                  maxLength: 10
                  items:
                    type: object
                    properties:
                      roleId:
                        type: string
                        description: The ID of the role to assign.
                      scope:
                        type: object
                        description: The scope of the role assignment.
                        properties:
                          communityIds:
                            type: array
                            description: Community internal id for the role assignment.
                            items:
                              type: string
                            maxLength: 250
                  example:
                    - roleId: role-12345
                      scope:
                        communityIds:
                          - community-67890
                  description: List of role assignments for the new admin.
              required:
                - username
                - displayName
                - password
                - roleAssignments
      responses:
        '200':
          $ref: '#/components/responses/root-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/admin/update:
    post:
      summary: Update admin user details
      description: Updates the details of an existing admin user.
      tags:
        - Admin
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the admin user to update.
                  example: 68259ab53825b47fcb5a518e
                displayName:
                  type: string
                  description: The updated display name for the admin.
                  example: test
                firstname:
                  type: string
                  description: The updated first name of the admin.
                  example: Test
                lastname:
                  type: string
                  description: The updated last name of the admin.
                  example: test
                permissions:
                  type: array
                  items:
                    type: string
                  description: Updated list of permissions assigned to the admin.
                  example:
                    - VIEW_DYNAMIC_UI
                    - VIEW_CHANNEL_MANAGEMENT
                    - MANAGE_CHANNEL
                    - MODERATE_CHANNEL
                    - VIEW_STORY_MANAGEMENT
                    - MANAGE_STORY
                    - VIEW_POST_AND_COMMENT_MANAGEMENT
                    - MODERATE_POST_AND_COMMENT
                    - MANAGE_POST_AND_COMMENT
                    - CAN_USE_BRAND_USERS
                    - CAN_MANAGE_BRAND_USERS
                    - CAN_MANAGE_GLOBAL_PINNED_POST
                    - CAN_MANAGE_PINNED_POST
                    - CAN_MANAGE_FEATURED_POST
                    - VIEW_LIVE_STREAMING_MANAGEMENT
                    - MANAGE_LIVE_STREAMING
                    - MODERATE_LIVE_STREAMING
                    - VIEW_COMMUNITY_MANAGEMENT
                    - MANAGE_COMMUNITY
                    - MODERATE_COMMUNITY
                    - DELETE_COMMUNITY
                    - VIEW_COMMUNITY_CATEGORY_MANAGEMENT
                    - MANAGE_COMMUNITY_CATEGORY
                    - VIEW_SPONSORED_CONTENT_MANAGEMENT
                    - MANAGE_SPONSORED_CONTENT
                    - MANAGE_AD_SETTING
                    - VIEW_USAGE
                    - VIEW_MODERATION_FEED
                    - MANAGE_ALLOW_LIST
                    - MANAGE_BLOCK_LIST
                    - MANAGE_IMAGE_MODERATION_SETTING
                    - MANAGE_LIVE_STREAMING_MODERATION_SETTING
                    - VIEW_USER_MANAGEMENT
                    - MANAGE_USER
                    - MODERATE_USER
                    - VIEW_USER_ROLE_MANAGEMENT
                    - MANAGE_USER_ROLE
                    - VIEW_ADMIN_USER
                    - MANAGE_ADMIN
                    - VIEW_ADMIN_ROLE
                    - VIEW_SETTING
                    - MANAGE_SETTING
                    - MANAGE_SECURITY
                avatarFileId:
                  type: string
                  description: The updated file ID of the avatar for the admin.
                  example: 3b05fe26320945438543a34e3d19e648
                roleAssignments:
                  type: array
                  items:
                    type: object
                    maxLength: 10
                    properties:
                      roleId:
                        type: string
                        description: The ID of the role to assign.
                      scope:
                        type: object
                        description: The scope of the role assignment.
                        properties:
                          communityIds:
                            type: array
                            maxLength: 250
                            description: Community internal id for the role assignment.
                            items:
                              type: string
                  example:
                    - roleId: role-12345
                      scope:
                        communityIds:
                          - community-67890
                  description: List of role assignments for the admin.
              required:
                - userId
                - displayName
                - firstname
                - lastname
                - permissions
                - avatarFileId
                - roleAssignments
      responses:
        '200':
          $ref: '#/components/responses/root-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/admin/roles:
    get:
      summary: Query admin roles
      description: Retrieve a list of admin roles based on query parameters.
      tags:
        - Admin
      security:
        - cookieAuth: []
      responses:
        '200':
          $ref: '#/components/responses/roles-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
    post:
      summary: Create a new admin role
      description: Creates a new admin role with the specified details and permissions. Role create from this API will have type as 'consoleAdmin'.
      tags:
        - Admin
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                  type: string
                  description: The unique ID of the role.
                  example: f74c96f3-eab5-4cda-b7a9-5d8e9402a43c
                  maxLength: 100
                displayName:
                  type: string
                  description: The display name of the role.
                  example: some role test
                  maxLength: 100
                description:
                  type: string
                  maxLength: 1024
                  description: A brief description of the role.
                  example: This is a test role
                permissions:
                  type: array
                  items:
                    type: string
                  description: List of permissions assigned to the role.
                  example:
                    - VIEW_DYNAMIC_UI
                    - VIEW_CHANNEL_MANAGEMENT
                    - MANAGE_CHANNEL
                    - MODERATE_CHANNEL
                    - VIEW_STORY_MANAGEMENT
                    - MANAGE_STORY
                    - VIEW_POST_AND_COMMENT_MANAGEMENT
                    - MODERATE_POST_AND_COMMENT
                    - MANAGE_POST_AND_COMMENT
                    - CAN_USE_BRAND_USERS
                    - CAN_MANAGE_BRAND_USERS
                    - CAN_MANAGE_GLOBAL_PINNED_POST
                    - CAN_MANAGE_PINNED_POST
                    - CAN_MANAGE_FEATURED_POST
                    - VIEW_LIVE_STREAMING_MANAGEMENT
                    - MANAGE_LIVE_STREAMING
                    - MODERATE_LIVE_STREAMING
                    - VIEW_COMMUNITY_MANAGEMENT
                    - MANAGE_COMMUNITY
                    - MODERATE_COMMUNITY
                    - DELETE_COMMUNITY
                    - VIEW_COMMUNITY_CATEGORY_MANAGEMENT
                    - MANAGE_COMMUNITY_CATEGORY
                    - VIEW_SPONSORED_CONTENT_MANAGEMENT
                    - MANAGE_SPONSORED_CONTENT
                    - MANAGE_AD_SETTING
                    - VIEW_USAGE
                    - VIEW_MODERATION_FEED
                    - MANAGE_ALLOW_LIST
                    - MANAGE_BLOCK_LIST
                    - MANAGE_IMAGE_MODERATION_SETTING
                    - MANAGE_LIVE_STREAMING_MODERATION_SETTING
                    - VIEW_USER_MANAGEMENT
                    - MANAGE_USER
                    - MODERATE_USER
                    - VIEW_USER_ROLE_MANAGEMENT
                    - MANAGE_USER_ROLE
                    - VIEW_ADMIN_USER
                    - MANAGE_ADMIN
                    - VIEW_ADMIN_ROLE
                    - VIEW_SETTING
                    - MANAGE_SETTING
                    - MANAGE_SECURITY
              required:
                - roleId
                - displayName
                - permissions
      responses:
        '200':
          $ref: '#/components/responses/roles-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
  /admin/v1/admin/roles/{roleId}:
    get:
      summary: Get admin role details
      description: Retrieve details of a specific admin role by its ID.
      tags:
        - Admin
      security:
        - cookieAuth: []
      parameters:
        - name: roleId
          in: path
          required: true
          description: The ID of the role to retrieve.
          schema:
            type: string
            example: f74c96f3-eab5-4cda-b7a9-5d8e9402a43c
      responses:
        '200':
          $ref: '#/components/responses/roles-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
    put:
      summary: Update an admin role
      description: Updates the details of an existing admin role.
      tags:
        - Admin
      security:
        - cookieAuth: []
      parameters:
        - name: roleId
          in: path
          required: true
          description: The ID of the role to update.
          schema:
            type: string
            example: f74c96f3-eab5-4cda-b7a9-5d8e9402a43c
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  description: The updated display name of the role.
                  example: updated role test
                  maxLength: 100
                description:
                  type: string
                  description: An updated brief description of the role.
                  example: This is an updated test role
                  maxLength: 1024
                permissions:
                  type: array
                  items:
                    type: string
                  description: Updated list of permissions assigned to the role.
                  example:
                    - VIEW_DYNAMIC_UI
                    - VIEW_CHANNEL_MANAGEMENT
                    - MANAGE_CHANNEL
                    - MODERATE_CHANNEL
                    - VIEW_STORY_MANAGEMENT
                    - MANAGE_STORY
                    - VIEW_POST_AND_COMMENT_MANAGEMENT
                    - MODERATE_POST_AND_COMMENT
                    - MANAGE_POST_AND_COMMENT
                    - CAN_USE_BRAND_USERS
                    - CAN_MANAGE_BRAND_USERS
                    - CAN_MANAGE_GLOBAL_PINNED_POST
                    - CAN_MANAGE_PINNED_POST
                    - CAN_MANAGE_FEATURED_POST
                    - VIEW_LIVE_STREAMING_MANAGEMENT
                    - MANAGE_LIVE_STREAMING
                    - MODERATE_LIVE_STREAMING
                    - VIEW_COMMUNITY_MANAGEMENT
                    - MANAGE_COMMUNITY
                    - MODERATE_COMMUNITY
                    - DELETE_COMMUNITY
                    - VIEW_COMMUNITY_CATEGORY_MANAGEMENT
                    - MANAGE_COMMUNITY_CATEGORY
                    - VIEW_SPONSORED_CONTENT_MANAGEMENT
                    - MANAGE_SPONSORED_CONTENT
                    - MANAGE_AD_SETTING
                    - VIEW_USAGE
                    - VIEW_MODERATION_FEED
                    - MANAGE_ALLOW_LIST
                    - MANAGE_BLOCK_LIST
                    - MANAGE_IMAGE_MODERATION_SETTING
                    - MANAGE_LIVE_STREAMING_MODERATION_SETTING
                    - VIEW_USER_MANAGEMENT
                    - MANAGE_USER
                    - MODERATE_USER
                    - VIEW_USER_ROLE_MANAGEMENT
                    - MANAGE_USER_ROLE
                    - VIEW_ADMIN_USER
                    - MANAGE_ADMIN
                    - VIEW_ADMIN_ROLE
                    - VIEW_SETTING
                    - MANAGE_SETTING
                    - MANAGE_SECURITY
              required:
                - roleId
                - displayName
                - permissions
      responses:
        '200':
          $ref: '#/components/responses/roles-post-response-200'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnAuthorizedError'
        '500':
          $ref: '#/components/responses/UnexpectedError'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    BearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
    basicAuth:
      type: http
      scheme: basic
  schemas:
    Content:
      type: object
      properties:
        contentId:
          type: string
          description: Internal ID of the content.
        contentPublicId:
          type: string
          description: Public ID of the content.
        contentType:
          type: string
          enum:
            - post
            - comment
          description: Type of the content.
        flagCount:
          type: integer
          description: Number of flags on the content.
        lastFlaggedAt:
          type: string
          format: date-time
          description: Timestamp of the last flag on the content.
        lastReviewedAt:
          type: string
          format: date-time
          description: Timestamp of the last review on the content.
        manualReview:
          type: object
          properties:
            reviewedType:
              type: string
              enum:
                - delete
                - clearFlag
              description: Type of manual review action.
            reviewedAt:
              type: string
              format: date-time
              description: Timestamp of the manual review action.
            reviewedBy:
              type: string
              description: Internal ID of the user who performed the manual review.
        tags:
          type: array
          items:
            type: string
            maxLength: 24
          max: 5
          description: List of tags associated with the content.
        aiModeration:
          type: object
          properties:
            type:
              type: string
              enum:
                - text
                - image
                - video
            moderatedAction:
              type: string
              enum:
                - delete
                - flag
              description: Type of AI moderation action.
            moderatedAt:
              type: string
              format: date-time
              description: Timestamp of the AI moderation action.
            categories:
              type: array
              items:
                type: object
                description: List of categories identified by AI moderation.
                properties:
                  name:
                    type: string
                    description: Category name.
                  score:
                    type: number
                    format: float
                    description: Confidence score of the category.
        targetId:
          type: string
          description: ID of the target (user or community) associated with the content.
        targetType:
          type: string
          description: Type of the target (user or community) associated with the content.
        userId:
          type: string
          description: ID of the user who created the content.
    Error:
      type: object
      properties:
        status:
          type: string
        code:
          type: number
        message:
          type: string
        data:
          type: object
          properties:
            detail:
              oneOf:
                - type: array
                  items:
                    type: string
                - type: object
    PremiumReportNetworkSetting:
      type: object
      properties:
        enabled:
          type: boolean
          default: false
    PremiumReport:
      type: object
      properties:
        fileName:
          type: string
          description: The name of the report file.
        lastModified:
          type: string
          format: date-time
          description: The date and time when the report was last modified.
        fileSize:
          type: integer
          description: The size of the report file in bytes.
  responses:
    root-response-200:
      description: |
        Moderation feeds information. To display actual content, use the contentId and contentType to get the content from the list API (ex. Post list, Comment list).
      content:
        application/json:
          schema:
            type: object
            properties:
              contents:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
              paging:
                type: object
                properties:
                  next:
                    type: string
                  previous:
                    type: string
              total:
                type: integer
                description: Total number of contents that match the filter.
                example: 100
    BadRequestError:
      description: Bad Request error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            code: 400000
            message: Bad Request.
    UnexpectedError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            code: 500000
            message: Unexpected error
    premium-reports-get-response-200:
      description: |
        Premium report settings response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PremiumReportNetworkSetting'
    root-get-response-200:
      description: |
        Premium report list.
      content:
        application/json:
          schema:
            type: object
            properties:
              reports:
                type: array
                items:
                  $ref: '#/components/schemas/PremiumReport'
              paging:
                type: object
                properties:
                  next:
                    type: string
    download-response-302:
      description: |
        Redirect to S3 signed URL for downloading the report.
      headers:
        Location:
          schema:
            type: string
            format: uri
          example: https://s3.amazonaws.com/bucket-name/report.csv?AWSAccessKeyId=AKIAIOSFODNN7EXAMPLE&Expires=1234567890&Signature=example
    list-networks-get-response-200:
      description: |
        List settings of networks that have the premium report enabled.
      content:
        application/json:
          schema:
            type: object
            properties:
              premiumReportSettings:
                type: array
                items:
                  type: object
                  properties:
                    networkId:
                      type: string
                      description: Network ID.
                      example: 507f1f77bcf86cd799439011
                    enabled:
                      type: boolean
                      description: Whether the premium report is enabled or not.
                      example: true
                description: List of settings of networks that have the premium report enabled.
    premium-reports-put-response-200:
      description: |
        Premium report settings response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PremiumReportNetworkSetting'
    root-post-response-200:
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: success
    UnAuthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            code: 400100
            message: Unauthorized
    roles-post-response-200:
      description: Successful response for create role API
      content:
        application/json:
          schema:
            type: object
            properties:
              roles:
                type: array
                items:
                  type: object
                  properties:
                    roleId:
                      type: string
                      description: The unique ID of the role.
                      example: test
                    displayName:
                      type: string
                      description: The display name of the role.
                      example: test
                    permissions:
                      type: array
                      items:
                        type: string
                      description: List of permissions assigned to the role.
                      example:
                        - VIEW_DYNAMIC_UI
                        - VIEW_CHANNEL_MANAGEMENT
                        - MANAGE_CHANNEL
                        - MODERATE_CHANNEL
                        - VIEW_STORY_MANAGEMENT
                        - MANAGE_STORY
                        - VIEW_POST_AND_COMMENT_MANAGEMENT
                        - MODERATE_POST_AND_COMMENT
                        - MANAGE_POST_AND_COMMENT
                        - CAN_USE_BRAND_USERS
                        - CAN_MANAGE_BRAND_USERS
                        - CAN_MANAGE_GLOBAL_PINNED_POST
                        - CAN_MANAGE_PINNED_POST
                        - CAN_MANAGE_FEATURED_POST
                        - VIEW_LIVE_STREAMING_MANAGEMENT
                        - MANAGE_LIVE_STREAMING
                        - MODERATE_LIVE_STREAMING
                        - VIEW_COMMUNITY_MANAGEMENT
                        - MANAGE_COMMUNITY
                        - MODERATE_COMMUNITY
                        - DELETE_COMMUNITY
                        - VIEW_COMMUNITY_CATEGORY_MANAGEMENT
                        - MANAGE_COMMUNITY_CATEGORY
                        - VIEW_SPONSORED_CONTENT_MANAGEMENT
                        - MANAGE_SPONSORED_CONTENT
                        - MANAGE_AD_SETTING
                        - VIEW_USAGE
                        - VIEW_MODERATION_FEED
                        - MANAGE_ALLOW_LIST
                        - MANAGE_BLOCK_LIST
                        - MANAGE_IMAGE_MODERATION_SETTING
                        - MANAGE_LIVE_STREAMING_MODERATION_SETTING
                        - VIEW_USER_MANAGEMENT
                        - MANAGE_USER
                        - MODERATE_USER
                        - VIEW_USER_ROLE_MANAGEMENT
                        - MANAGE_USER_ROLE
                        - VIEW_ADMIN_USER
                        - MANAGE_ADMIN
                        - VIEW_ADMIN_ROLE
                        - VIEW_SETTING
                        - MANAGE_SETTING
                        - MANAGE_SECURITY
                    isDeleted:
                      type: boolean
                      description: Indicates if the role is deleted.
                      example: false
                    type:
                      type: string
                      description: The type of the role.
                      example: consoleAdmin
                    description:
                      type: string
                      description: A brief description of the role.
                      example: test
    NotFoundError:
      description: Resource Not Found error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            status: error
            code: 400400
            message: Resource Not Found.
